version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${$POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - ${5433}:${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgres

  app:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - ${PORT}:${PORT}
    stdin_open: true
    tty: true

volumes:
  db:
